vfh:
  s: 72
  t_high: 60.5
  t_low: 20
  r_enl: 2
  cost_params: [5,2,2]
  target: [20,0]
  t_obst: 60
  
safety:
  ultrasonic_threshold: 2

sensor_feedback:
  show_debug_info: false

drone_control:
  alt: 2.5

depth_generation:
  intensity: 0.1
